# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 864)
        MainWindow.setStyleSheet("color:white;\n"
"background-color:rgb(33, 37, 41)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bool_btn = QtWidgets.QPushButton(self.centralwidget)
        self.bool_btn.setGeometry(QtCore.QRect(330, 180, 90, 32))
        self.bool_btn.setStyleSheet("color:white")
        self.bool_btn.setObjectName("bool_btn")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setEnabled(True)
        self.Title.setGeometry(QtCore.QRect(370, 0, 291, 41))
        self.Title.setMinimumSize(QtCore.QSize(291, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title.setStyleSheet("color:white")
        self.Title.setObjectName("Title")
        self.Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.Title_2.setEnabled(True)
        self.Title_2.setGeometry(QtCore.QRect(150, 50, 100, 41))
        self.Title_2.setMinimumSize(QtCore.QSize(100, 0))
        self.Title_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_2.setFont(font)
        self.Title_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_2.setStyleSheet("color:white;\n"
"widht:300px")
        self.Title_2.setObjectName("Title_2")
        self.Title_3 = QtWidgets.QLabel(self.centralwidget)
        self.Title_3.setEnabled(True)
        self.Title_3.setGeometry(QtCore.QRect(700, 40, 100, 41))
        self.Title_3.setMinimumSize(QtCore.QSize(100, 0))
        self.Title_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_3.setFont(font)
        self.Title_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_3.setStyleSheet("color:white;\n"
"widht:300px")
        self.Title_3.setObjectName("Title_3")
        self.bool_req = QtWidgets.QLineEdit(self.centralwidget)
        self.bool_req.setGeometry(QtCore.QRect(120, 130, 251, 26))
        self.bool_req.setStyleSheet("color:white")
        self.bool_req.setObjectName("bool_req")
        self.vect_req = QtWidgets.QLineEdit(self.centralwidget)
        self.vect_req.setGeometry(QtCore.QRect(650, 130, 281, 26))
        self.vect_req.setStyleSheet("color:white")
        self.vect_req.setObjectName("vect_req")
        self.Title_4 = QtWidgets.QLabel(self.centralwidget)
        self.Title_4.setEnabled(True)
        self.Title_4.setGeometry(QtCore.QRect(10, 120, 100, 41))
        self.Title_4.setMinimumSize(QtCore.QSize(100, 0))
        self.Title_4.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_4.setFont(font)
        self.Title_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_4.setStyleSheet("color:white")
        self.Title_4.setObjectName("Title_4")
        self.Title_5 = QtWidgets.QLabel(self.centralwidget)
        self.Title_5.setEnabled(True)
        self.Title_5.setGeometry(QtCore.QRect(540, 120, 100, 41))
        self.Title_5.setMinimumSize(QtCore.QSize(100, 0))
        self.Title_5.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_5.setFont(font)
        self.Title_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_5.setStyleSheet("color:white")
        self.Title_5.setObjectName("Title_5")
        self.vect_btn = QtWidgets.QPushButton(self.centralwidget)
        self.vect_btn.setGeometry(QtCore.QRect(880, 180, 90, 32))
        self.vect_btn.setStyleSheet("color:white")
        self.vect_btn.setObjectName("vect_btn")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(624, 180, 221, 31))
        self.comboBox.setStyleSheet("\n"
"   display: block;\n"
"    color: white;\n"
"    box-sizing: border-box;\n"
"    margin: 0;\n"
"    border: 1px solid #aaa;\n"
"    box-shadow: 0 1px 0 1px rgba(0,0,0,.04);\n"
"    -moz-appearance: none;\n"
"    -webkit-appearance: none;\n"
"    appearance: none;\n"
"    background-color: rgb(33, 37, 41);\n"
"  \n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.bool_result = QtWidgets.QTextEdit(self.centralwidget)
        self.bool_result.setGeometry(QtCore.QRect(10, 230, 411, 291))
        self.bool_result.setObjectName("bool_result")
        self.vect_result = QtWidgets.QTextEdit(self.centralwidget)
        self.vect_result.setGeometry(QtCore.QRect(520, 230, 451, 291))
        self.vect_result.setObjectName("vect_result")
        self.Title_6 = QtWidgets.QLabel(self.centralwidget)
        self.Title_6.setEnabled(True)
        self.Title_6.setGeometry(QtCore.QRect(440, 530, 291, 41))
        self.Title_6.setMinimumSize(QtCore.QSize(291, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_6.setFont(font)
        self.Title_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_6.setObjectName("Title_6")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 570, 311, 231))
        self.tableWidget.setMinimumSize(QtCore.QSize(311, 0))
        self.tableWidget.setStyleSheet("width:400px")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.Title_7 = QtWidgets.QLabel(self.centralwidget)
        self.Title_7.setEnabled(True)
        self.Title_7.setGeometry(QtCore.QRect(330, 560, 291, 41))
        self.Title_7.setMinimumSize(QtCore.QSize(291, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_7.setFont(font)
        self.Title_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_7.setObjectName("Title_7")
        self.Title_8 = QtWidgets.QLabel(self.centralwidget)
        self.Title_8.setEnabled(True)
        self.Title_8.setGeometry(QtCore.QRect(830, 560, 291, 41))
        self.Title_8.setMinimumSize(QtCore.QSize(291, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_8.setFont(font)
        self.Title_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_8.setObjectName("Title_8")
        self.Title_9 = QtWidgets.QLabel(self.centralwidget)
        self.Title_9.setEnabled(True)
        self.Title_9.setGeometry(QtCore.QRect(330, 770, 291, 41))
        self.Title_9.setMinimumSize(QtCore.QSize(291, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_9.setFont(font)
        self.Title_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_9.setObjectName("Title_9")
        self.Title_10 = QtWidgets.QLabel(self.centralwidget)
        self.Title_10.setEnabled(True)
        self.Title_10.setGeometry(QtCore.QRect(620, 770, 291, 41))
        self.Title_10.setMinimumSize(QtCore.QSize(291, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_10.setFont(font)
        self.Title_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_10.setObjectName("Title_10")
        self.selected_query = QtWidgets.QLineEdit(self.centralwidget)
        self.selected_query.setEnabled(False)
        self.selected_query.setGeometry(QtCore.QRect(450, 570, 361, 26))
        self.selected_query.setObjectName("selected_query")
        self.index = QtWidgets.QLineEdit(self.centralwidget)
        self.index.setEnabled(False)
        self.index.setGeometry(QtCore.QRect(900, 570, 61, 26))
        self.index.setObjectName("index")
        self.Evaluate = QtWidgets.QPushButton(self.centralwidget)
        self.Evaluate.setEnabled(False)
        self.Evaluate.setGeometry(QtCore.QRect(890, 780, 90, 32))
        self.Evaluate.setObjectName("Evaluate")
        self.Title_11 = QtWidgets.QLabel(self.centralwidget)
        self.Title_11.setEnabled(True)
        self.Title_11.setGeometry(QtCore.QRect(330, 600, 150, 41))
        self.Title_11.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_11.setFont(font)
        self.Title_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_11.setObjectName("Title_11")
        self.Title_12 = QtWidgets.QLabel(self.centralwidget)
        self.Title_12.setEnabled(True)
        self.Title_12.setGeometry(QtCore.QRect(480, 600, 291, 41))
        self.Title_12.setMinimumSize(QtCore.QSize(291, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_12.setFont(font)
        self.Title_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_12.setObjectName("Title_12")
        self.Supposed = QtWidgets.QTableWidget(self.centralwidget)
        self.Supposed.setGeometry(QtCore.QRect(340, 640, 101, 141))
        self.Supposed.setObjectName("Supposed")
        self.Supposed.setColumnCount(1)
        self.Supposed.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Supposed.setHorizontalHeaderItem(0, item)
        self.Systeme = QtWidgets.QTableWidget(self.centralwidget)
        self.Systeme.setGeometry(QtCore.QRect(480, 640, 501, 141))
        self.Systeme.setObjectName("Systeme")
        self.Systeme.setColumnCount(5)
        self.Systeme.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Systeme.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Systeme.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Systeme.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Systeme.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Systeme.setHorizontalHeaderItem(4, item)
        self.rappel = QtWidgets.QLineEdit(self.centralwidget)
        self.rappel.setEnabled(True)
        self.rappel.setGeometry(QtCore.QRect(390, 780, 161, 26))
        self.rappel.setObjectName("rappel")
        self.precision = QtWidgets.QLineEdit(self.centralwidget)
        self.precision.setEnabled(True)
        self.precision.setGeometry(QtCore.QRect(690, 780, 141, 26))
        self.precision.setObjectName("precision")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bool_btn.setText(_translate("MainWindow", "Run"))
        self.Title.setText(_translate("MainWindow", "Recherche d\'infromations"))
        self.Title_2.setText(_translate("MainWindow", "Boolean model"))
        self.Title_3.setText(_translate("MainWindow", "Vectoriel model"))
        self.Title_4.setText(_translate("MainWindow", "Request :"))
        self.Title_5.setText(_translate("MainWindow", "Request :"))
        self.vect_btn.setText(_translate("MainWindow", "Run"))
        self.comboBox.setItemText(0, _translate("MainWindow", "produit_interne"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Coef_de_Dice"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Mesure_de_cosinus"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Mesure_de_jaccard"))
        self.Title_6.setText(_translate("MainWindow", "Evaluation"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Query"))
        self.Title_7.setText(_translate("MainWindow", "Selected query :"))
        self.Title_8.setText(_translate("MainWindow", "Index :"))
        self.Title_9.setText(_translate("MainWindow", "Rappel :"))
        self.Title_10.setText(_translate("MainWindow", "Precision :"))
        self.Evaluate.setText(_translate("MainWindow", "Evaluate"))
        self.Title_11.setText(_translate("MainWindow", "Supposed return :"))
        self.Title_12.setText(_translate("MainWindow", "Systeme return"))
        item = self.Supposed.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Doc"))
        item = self.Systeme.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Doc"))
        item = self.Systeme.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PI"))
        item = self.Systeme.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CD"))
        item = self.Systeme.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "MC"))
        item = self.Systeme.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "MJ"))
