# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bool_btn = QtWidgets.QPushButton(self.centralwidget)
        self.bool_btn.setGeometry(QtCore.QRect(330, 180, 90, 32))
        self.bool_btn.setObjectName("bool_btn")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setEnabled(True)
        self.Title.setGeometry(QtCore.QRect(370, 0, 291, 41))
        self.Title.setMinimumSize(QtCore.QSize(291, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title.setObjectName("Title")
        self.Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.Title_2.setEnabled(True)
        self.Title_2.setGeometry(QtCore.QRect(150, 50, 100, 41))
        self.Title_2.setMinimumSize(QtCore.QSize(100, 0))
        self.Title_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_2.setFont(font)
        self.Title_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_2.setObjectName("Title_2")
        self.Title_3 = QtWidgets.QLabel(self.centralwidget)
        self.Title_3.setEnabled(True)
        self.Title_3.setGeometry(QtCore.QRect(700, 40, 100, 41))
        self.Title_3.setMinimumSize(QtCore.QSize(100, 0))
        self.Title_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_3.setFont(font)
        self.Title_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_3.setObjectName("Title_3")
        self.bool_req = QtWidgets.QLineEdit(self.centralwidget)
        self.bool_req.setGeometry(QtCore.QRect(70, 130, 251, 26))
        self.bool_req.setObjectName("bool_req")
        self.vect_req = QtWidgets.QLineEdit(self.centralwidget)
        self.vect_req.setGeometry(QtCore.QRect(600, 130, 281, 26))
        self.vect_req.setObjectName("vect_req")
        self.Title_4 = QtWidgets.QLabel(self.centralwidget)
        self.Title_4.setEnabled(True)
        self.Title_4.setGeometry(QtCore.QRect(10, 120, 100, 41))
        self.Title_4.setMinimumSize(QtCore.QSize(100, 0))
        self.Title_4.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_4.setFont(font)
        self.Title_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_4.setObjectName("Title_4")
        self.Title_5 = QtWidgets.QLabel(self.centralwidget)
        self.Title_5.setEnabled(True)
        self.Title_5.setGeometry(QtCore.QRect(540, 120, 100, 41))
        self.Title_5.setMinimumSize(QtCore.QSize(100, 0))
        self.Title_5.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_5.setFont(font)
        self.Title_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_5.setObjectName("Title_5")
        self.vect_btn = QtWidgets.QPushButton(self.centralwidget)
        self.vect_btn.setGeometry(QtCore.QRect(880, 180, 90, 32))
        self.vect_btn.setObjectName("vect_btn")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(700, 180, 161, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.bool_result = QtWidgets.QTextEdit(self.centralwidget)
        self.bool_result.setGeometry(QtCore.QRect(10, 230, 411, 291))
        self.bool_result.setObjectName("bool_result")
        self.vect_result = QtWidgets.QTextEdit(self.centralwidget)
        self.vect_result.setGeometry(QtCore.QRect(520, 230, 451, 291))
        self.vect_result.setObjectName("vect_result")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(570, 190, 83, 26))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bool_btn.setText(_translate("MainWindow", "Run"))
        self.Title.setText(_translate("MainWindow", "Recherche d\'infromations"))
        self.Title_2.setText(_translate("MainWindow", "Boolean model"))
        self.Title_3.setText(_translate("MainWindow", "Vectoriel model"))
        self.Title_4.setText(_translate("MainWindow", "Request :"))
        self.Title_5.setText(_translate("MainWindow", "Request :"))
        self.vect_btn.setText(_translate("MainWindow", "Run"))
        self.comboBox.setItemText(0, _translate("MainWindow", "produit_interne"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Coef_de_Dice"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Mesure_de_cosinus"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Mesure_de_jaccard"))
        self.checkBox.setText(_translate("MainWindow", "Evaluate"))
